In [2]:
import pandas as pd

In [3]:
NEWS_COLUMNS = [
    "news_id",
    "category",
    "subcategory",
    "title",
    "abstract",
    "url",
    "title_entities",
    "abstract_entities"
]

In [4]:
news = pd.read_csv(
    "../data/raw/train/news.tsv",
    sep="\t",
    names=NEWS_COLUMNS
)

In [5]:
news.head()

,news_id,category,subcategory,title,abstract,url,title_entities,abstract_entities
0,N55528,lifestyle,lifestyleroyals,"The Brands Queen Elizabeth, Prince Charles, an...","Shop the notebooks, jackets, and more that the...",https://assets.msn.com/labs/mind/AAGH0ET.html,"[{""Label"": ""Prince Philip, Duke of Edinburgh"",...",[]
1,N19639,health,weightloss,50 Worst Habits For Belly Fat,These seemingly harmless habits are holding yo...,https://assets.msn.com/labs/mind/AAB19MK.html,"[{""Label"": ""Adipose tissue"", ""Type"": ""C"", ""Wik...","[{""Label"": ""Adipose tissue"", ""Type"": ""C"", ""Wik..."
2,N61837,news,newsworld,The Cost of Trump's Aid Freeze in the Trenches...,Lt. Ivan Molchanets peeked over a parapet of s...,https://assets.msn.com/labs/mind/AAJgNsz.html,[],"[{""Label"": ""Ukraine"", ""Type"": ""G"", ""WikidataId..."
3,N53526,health,voices,I Was An NBA Wife. Here's How It Affected My M...,"I felt like I was a fraud, and being an NBA wi...",https://assets.msn.com/labs/mind/AACk2N6.html,[],"[{""Label"": ""National Basketball Association"", ..."
4,N38324,health,medical,"How to Get Rid of Skin Tags, According to a De...","They seem harmless, but there's a very good re...",https://assets.msn.com/labs/mind/AAAKEkt.html,"[{""Label"": ""Skin tag"", ""Type"": ""C"", ""WikidataI...","[{""Label"": ""Skin tag"", ""Type"": ""C"", ""WikidataI..."

In [6]:
news.shape

(51282, 8)

In [7]:
news.columns

Index(['news_id', 'category', 'subcategory', 'title', 'abstract', 'url',
       'title_entities', 'abstract_entities'],
      dtype='str')

In [8]:
news.isnull().sum()

news_id                 0
category                0
subcategory             0
title                   0
abstract             2666
url                     0
title_entities          3
abstract_entities       4
dtype: int64

In [9]:
news['category'].value_counts()

category
news             15774
sports           14510
finance           3107
foodanddrink      2551
lifestyle         2479
travel            2350
video             2068
weather           2048
health            1885
autos             1639
tv                 889
music              769
movies             606
entertainment      587
kids                17
middleeast           2
northamerica         1
Name: count, dtype: int64

In [10]:
news['category'].value_counts(normalize=True).head(10)

category
news            0.307593
sports          0.282945
finance         0.060587
foodanddrink    0.049745
lifestyle       0.048341
travel          0.045825
video           0.040326
weather         0.039936
health          0.036758
autos           0.031961
Name: proportion, dtype: float64

In [11]:
news["subcategory"].value_counts().head(15)

subcategory
newsus                      6564
football_nfl                5420
newspolitics                2826
newscrime                   2254
weathertopstories           2047
newsworld                   1720
football_ncaa               1665
baseball_mlb                1661
basketball_nba              1555
newsscienceandtechnology    1210
news                        1185
newstrends                  1176
more_sports                 1065
travelarticle               1042
travelnews                   902
Name: count, dtype: int64

In [12]:
news["title_length"] = news["title"].str.split().str.len()

In [13]:
news['title_length'].describe()

count    51282.000000
mean        10.754417
std          3.265311
min          1.000000
25%          9.000000
50%         10.000000
75%         13.000000
max         57.000000
Name: title_length, dtype: float64

In [14]:
news.groupby('category')['subcategory'].unique()

category
autos            [autosenthusiasts, autossuvs, autosnews, autos...
entertainment    [gaming, celebrity, entertainment-celebrity, e...
finance          [finance-real-estate, finance-saving-investing...
foodanddrink     [recipes, quickandeasy, tipsandtricks, newstre...
health           [weightloss, voices, medical, nutrition, welln...
kids                 [fun, video, science, people-places, animals]
lifestyle        [lifestyleroyals, lifestylepetsanimals, lifest...
middleeast                                [middleeast-top-stories]
movies           [movies-gallery, movievideo, movies-celebrity,...
music            [musicnews, music-gallery, musicvideos, music-...
news             [newsworld, newsscienceandtechnology, newspoli...
northamerica                                  [northamerica-video]
sports           [football_nfl, golf, basketball_nba, basketbal...
travel           [travelarticle, traveltripideas, travelnews, t...
tv               [tv-gallery, tv-celebrity, tvnews, humor, tv-r...
video            [viral, news, animals, popculture, science, pe...
weather                 [weathertopstories, weatherfullscreenmaps]
Name: subcategory, dtype: object

In [15]:
news[news['category']=='sports']['subcategory'].unique()

<StringArray>
[          'football_nfl',                   'golf',         'basketball_nba',
        'basketball_ncaa',            'more_sports',                 'racing',
           'baseball_mlb',          'football_ncaa',                 'tennis',
                    'mma',    'football_nfl_videos',                 'soccer',
               'outdoors',    'baseball_mlb_videos',   'football_ncaa_videos',
          'icehockey_nhl',             'boxing-mma',                 'boxing',
             'soccer_mls', 'basketball_ncaa_videos',             'soccer_epl',
        'olympics-videos',        'basketball_wnba',             'golfvideos',
            'sports_news',                 'mmaufc',  'basketball_nba_videos',
            'othersports',               'baseball',            'soccer_bund',
            'tennis_intl']
Length: 31, dtype: str

In [16]:
news["abstract_length"] = news["abstract"].fillna("").str.split().str.len()

In [17]:
news["abstract_length"].describe()

count    51282.000000
mean        34.293319
std         26.542819
min          0.000000
25%         15.000000
50%         24.000000
75%         62.000000
max        474.000000
Name: abstract_length, dtype: float64

In [18]:
(news['abstract_length']==0).sum()

np.int64(2666)

In [19]:
news['title'].duplicated().sum()

np.int64(848)

In [20]:
news['news_id'].duplicated().sum()

np.int64(0)

In [21]:
news[news["title"].duplicated(keep=False)][
    ["news_id", "title", "category", "subcategory"]
].sort_values("title").head(20)

,news_id,title,category,subcategory
35832,N34049,'A game-changer': Titans' expansion project wi...,sports,football_nfl
33999,N56680,'A game-changer': Titans' expansion project wi...,sports,football_nfl
45242,N16531,'Baby Trump' balloon slashed at Alabama appear...,news,newscrime
42376,N1034,'Baby Trump' balloon slashed at Alabama appear...,news,newsus
39222,N22807,"'Beautiful day': Lots of sunshine, cooler temp...",weather,weathertopstories
48423,N14525,"'Beautiful day': Lots of sunshine, cooler temp...",weather,weathertopstories
38964,N4863,'Go somewhere else and file': Judge tosses out...,video,news
47495,N41282,'Go somewhere else and file': Judge tosses out...,news,newspolitics
50781,N9523,'Hidden figures' to receive Congressional Gold...,travel,travelarticle
48464,N9738,'Hidden figures' to receive Congressional Gold...,news,newsus
41498,N32611,'Jeopardy!' unbelievably had sign-stealing clu...,sports,baseball_mlb
42293,N34315,'Jeopardy!' unbelievably had sign-stealing clu...,sports,baseball_mlb
32328,N23466,'Leave now': Australians urged to evacuate as ...,video,news
51150,N46729,'Leave now': Australians urged to evacuate as ...,news,newsworld
8475,N48343,'See you at the polls': Trump and Pelosi have ...,news,newspolitics
8466,N52346,'See you at the polls': Trump and Pelosi have ...,news,newspolitics
30818,N54917,'The better team in all three phases': how Mic...,sports,football_ncaa
29205,N13122,'The better team in all three phases': how Mic...,sports,more_sports
48677,N8849,'We were blindsided': NC vet and his wife deal...,health,medical
7929,N9209,'We were blindsided': NC vet and his wife deal...,health,medical

In [22]:
BEHAVIOR_COLUMNS = [
    "impression_id",
    "user_id",
    "time",
    "history",
    "impressions"
]

In [23]:
behaviors = pd.read_csv(
    "../data/raw/train/behaviors.tsv",
    sep="\t",
    names=BEHAVIOR_COLUMNS
)

In [24]:
behaviors.head()

,impression_id,user_id,time,history,impressions
0,1,U13740,11/11/2019 9:05:58 AM,N55189 N42782 N34694 N45794 N18445 N63302 N104...,N55689-1 N35729-0
1,2,U91836,11/12/2019 6:11:30 PM,N31739 N6072 N63045 N23979 N35656 N43353 N8129...,N20678-0 N39317-0 N58114-0 N20495-0 N42977-0 N...
2,3,U73700,11/14/2019 7:01:48 AM,N10732 N25792 N7563 N21087 N41087 N5445 N60384...,N50014-0 N23877-0 N35389-0 N49712-0 N16844-0 N...
3,4,U34670,11/11/2019 5:28:05 AM,N45729 N2203 N871 N53880 N41375 N43142 N33013 ...,N35729-0 N33632-0 N49685-1 N27581-0
4,5,U8125,11/12/2019 4:11:21 PM,N10078 N56514 N14904 N33740,N39985-0 N36050-0 N16096-0 N8400-1 N22407-0 N6...

In [25]:
behaviors.iloc[0]

impression_id                                                    1
user_id                                                     U13740
time                                         11/11/2019 9:05:58 AM
history          N55189 N42782 N34694 N45794 N18445 N63302 N104...
impressions                                      N55689-1 N35729-0
Name: 0, dtype: object

In [26]:
behaviors.iloc[0]["history"]

'N55189 N42782 N34694 N45794 N18445 N63302 N10414 N19347 N31801'

In [27]:
behaviors.iloc[0]["impressions"]

'N55689-1 N35729-0'

In [28]:
behaviors.iloc[0]["impressions"].split()

['N55689-1', 'N35729-0']

In [29]:
behaviors.iloc[0]["impressions"].split()[0].split("-")

['N55689', '1']

In [30]:
parsed = [
    (news_id, int(label))
    for news_id, label in [
        item.split("-")
        for item in behaviors.iloc[0]["impressions"].split()
    ]
]

In [31]:
parsed

[('N55689', 1), ('N35729', 0)]

In [32]:
from collections import Counter

In [33]:
Counter(label for _, label in parsed)

Counter({1: 1, 0: 1})

In [34]:
behaviors["num_impressions"] = behaviors["impressions"].apply(
    lambda x: len(x.split())
)

In [35]:
behaviors["num_impressions"] = behaviors["impressions"].apply(
    lambda x: len(x.split())
)

In [36]:
behaviors["num_impressions"].describe()

count    156965.000000
mean         37.227688
std          38.594148
min           2.000000
25%          10.000000
50%          24.000000
75%          51.000000
max         299.000000
Name: num_impressions, dtype: float64

In [37]:
behaviors["history_length"] = behaviors["history"].fillna("").apply(
    lambda x: len(x.split()) if x else 0
)

In [38]:
behaviors["history_length"].describe()

count    156965.000000
mean         32.539987
std          40.267607
min           0.000000
25%           8.000000
50%          19.000000
75%          42.000000
max         558.000000
Name: history_length, dtype: float64

In [39]:
behaviors["history_length"].describe()

count    156965.000000
mean         32.539987
std          40.267607
min           0.000000
25%           8.000000
50%          19.000000
75%          42.000000
max         558.000000
Name: history_length, dtype: float64

In [40]:
(behaviors["history_length"] == 0).sum()

np.int64(3238)

In [41]:
behaviors["user_id"].nunique()

50000

In [42]:
behaviors["impression_id"].nunique()

156965

In [43]:
behaviors["clicks"] = behaviors["impressions"].apply(
    lambda x: sum(int(item.split("-")[1]) for item in x.split())
)

In [44]:
behaviors['num_impressions'].head()

0     2
1    11
2    36
3     4
4    69
Name: num_impressions, dtype: int64

In [46]:
behaviors['clicks'].head()

0    1
1    1
2    1
3    1
4    1
Name: clicks, dtype: int64

In [47]:
total_clicks = behaviors["clicks"].sum()

In [48]:
total_impressions = behaviors["num_impressions"].sum()

In [49]:
ctr = total_clicks / total_impressions
ctr

np.float64(0.040446010948338)

In [50]:
behaviors['impressions']

0                                         N55689-1 N35729-0
1         N20678-0 N39317-0 N58114-0 N20495-0 N42977-0 N...
2         N50014-0 N23877-0 N35389-0 N49712-0 N16844-0 N...
3                       N35729-0 N33632-0 N49685-1 N27581-0
4         N39985-0 N36050-0 N16096-0 N8400-1 N22407-0 N6...
                                ...
156960    N2235-0 N22975-0 N64037-0 N47652-0 N11378-0 N4...
156961    N3841-0 N61571-0 N58813-0 N28213-0 N4428-0 N25...
156962    N55913-0 N62318-0 N53515-0 N10960-0 N9135-0 N5...
156963    N6219-0 N3663-0 N31147-0 N58363-0 N4107-0 N457...
156964                  N61233-0 N33828-1 N19661-0 N41934-0
Name: impressions, Length: 156965, dtype: str

In [3]:
import pandas as pd

BEHAVIOR_COLUMNS = [
    "impression_id",
    "user_id",
    "time",
    "history",
    "impressions"
]

behaviors = pd.read_csv(
    "../data/raw/valid/behaviors.tsv",
    sep="\t",
    names=BEHAVIOR_COLUMNS
)

behaviors["time"] = pd.to_datetime(
    behaviors["time"],
    format="%m/%d/%Y %I:%M:%S %p"
)

user_counts = behaviors.groupby("user_id").size()

print(user_counts.describe())

print("\nUsers with more than one behavior:")
print((user_counts > 1).sum())

print("\nMaximum behaviors for one user:")
print(user_counts.max())

count    50000.000000
mean         1.463040
std          0.909907
min          1.000000
25%          1.000000
50%          1.000000
75%          2.000000
max         18.000000
dtype: float64

Users with more than one behavior:
14826

Maximum behaviors for one user:
18

In [4]:
user_counts = behaviors.groupby("user_id").size()

user_id = user_counts.idxmax()

user_data = (
    behaviors[behaviors["user_id"] == user_id]
    .sort_values("time")
)

print("User:", user_id)
print("Number of events:", len(user_data))

user_data[
    ["time", "history", "impressions"]
]

User: U38741
Number of events: 18

,time,history,impressions
5057,2019-11-15 06:54:31,N58794 N37211 N48304 N41854 N16317 N20297 N225...,N41946-1 N6638-0 N30290-0 N53242-0 N48487-0 N3...
50956,2019-11-15 07:15:28,N58794 N37211 N48304 N41854 N16317 N20297 N225...,N58264-0 N33638-0 N23513-0 N20187-0 N27738-0 N...
72991,2019-11-15 07:36:34,N58794 N37211 N48304 N41854 N16317 N20297 N225...,N42844-0 N35216-0 N32536-0 N20187-0 N20036-1 N...
68952,2019-11-15 09:40:21,N58794 N37211 N48304 N41854 N16317 N20297 N225...,N58251-0 N53572-0 N37352-0 N49285-0 N55237-0 N...
53701,2019-11-15 09:58:15,N58794 N37211 N48304 N41854 N16317 N20297 N225...,N42844-0 N49285-0 N55237-0 N58251-0 N30290-0 N...
4009,2019-11-15 10:06:32,N58794 N37211 N48304 N41854 N16317 N20297 N225...,N31958-0 N37352-0 N53572-0 N58251-0 N50775-1 N...
40628,2019-11-15 10:12:16,N58794 N37211 N48304 N41854 N16317 N20297 N225...,N13408-0 N37352-0 N62365-0 N58251-0 N9775-0 N3...
30351,2019-11-15 10:23:02,N58794 N37211 N48304 N41854 N16317 N20297 N225...,N62365-0 N37352-0 N53572-0 N30290-0 N47383-1 N...
52268,2019-11-15 10:49:12,N58794 N37211 N48304 N41854 N16317 N20297 N225...,N58264-0 N28582-0 N53572-0 N58098-0 N11930-0 N...
64544,2019-11-15 10:55:11,N58794 N37211 N48304 N41854 N16317 N20297 N225...,N31958-0 N55237-0 N58251-0 N53572-0 N29862-1
45743,2019-11-15 11:19:56,N58794 N37211 N48304 N41854 N16317 N20297 N225...,N58251-0 N436-0 N65145-0 N7993-0 N58098-0 N319...
30703,2019-11-15 11:48:54,N58794 N37211 N48304 N41854 N16317 N20297 N225...,N58251-0 N53572-0 N37352-0 N6400-0 N24802-1
24559,2019-11-15 12:44:09,N58794 N37211 N48304 N41854 N16317 N20297 N225...,N60799-0 N6916-0 N11974-0 N65145-0 N58656-0 N9...
11183,2019-11-15 13:01:37,N58794 N37211 N48304 N41854 N16317 N20297 N225...,N11390-0 N53572-0 N24802-1 N5472-0 N56434-0 N2...
51857,2019-11-15 13:11:50,N58794 N37211 N48304 N41854 N16317 N20297 N225...,N38215-0 N9991-0 N11390-0 N60215-0 N27057-0 N6...
18058,2019-11-15 13:27:12,N58794 N37211 N48304 N41854 N16317 N20297 N225...,N56434-0 N48740-1 N55237-0 N11390-0 N5472-0 N4...
67886,2019-11-15 14:00:39,N58794 N37211 N48304 N41854 N16317 N20297 N225...,N46749-0 N49285-0 N29862-0 N24802-0 N1952-0 N5...
710,2019-11-15 15:31:37,N58794 N37211 N48304 N41854 N16317 N20297 N225...,N12409-0 N28640-0 N45057-0 N60762-0 N512-0 N20...

In [5]:
for i, row in user_data.iterrows():
    history = row["history"].split() if pd.notna(row["history"]) else []

    clicked_now = [
        item.split("-")[0]
        for item in row["impressions"].split()
        if item.endswith("-1")
    ]

    print(
        row["time"],
        "| history length:", len(history),
        "| clicked now:", clicked_now
    )

2019-11-15 06:54:31 | history length: 256 | clicked now: ['N41946']
2019-11-15 07:15:28 | history length: 256 | clicked now: ['N9991', 'N41946', 'N29107']
2019-11-15 07:36:34 | history length: 256 | clicked now: ['N20036']
2019-11-15 09:40:21 | history length: 256 | clicked now: ['N5472']
2019-11-15 09:58:15 | history length: 256 | clicked now: ['N19990']
2019-11-15 10:06:32 | history length: 256 | clicked now: ['N50775']
2019-11-15 10:12:16 | history length: 256 | clicked now: ['N6916']
2019-11-15 10:23:02 | history length: 256 | clicked now: ['N47383']
2019-11-15 10:49:12 | history length: 256 | clicked now: ['N36673', 'N64392']
2019-11-15 10:55:11 | history length: 256 | clicked now: ['N29862']
2019-11-15 11:19:56 | history length: 256 | clicked now: ['N31519', 'N34130', 'N51470', 'N38215']
2019-11-15 11:48:54 | history length: 256 | clicked now: ['N24802']
2019-11-15 12:44:09 | history length: 256 | clicked now: ['N37204', 'N47068']
2019-11-15 13:01:37 | history length: 256 | clicked now: ['N24802']
2019-11-15 13:11:50 | history length: 256 | clicked now: ['N6400', 'N60939']
2019-11-15 13:27:12 | history length: 256 | clicked now: ['N48740']
2019-11-15 14:00:39 | history length: 256 | clicked now: ['N15347']
2019-11-15 15:31:37 | history length: 256 | clicked now: ['N52492']

In [6]:
rows = user_data.reset_index(drop=True)

for i in range(1, len(rows)):
    prev_clicks = {
        item.split("-")[0]
        for item in rows.iloc[i - 1]["impressions"].split()
        if item.endswith("-1")
    }

    current_history = set(
        rows.iloc[i]["history"].split()
    )

    print(
        rows.iloc[i]["time"],
        "| previous clicks now in history:",
        prev_clicks & current_history
    )

2019-11-15 07:15:28 | previous clicks now in history: set()
2019-11-15 07:36:34 | previous clicks now in history: set()
2019-11-15 09:40:21 | previous clicks now in history: set()
2019-11-15 09:58:15 | previous clicks now in history: set()
2019-11-15 10:06:32 | previous clicks now in history: set()
2019-11-15 10:12:16 | previous clicks now in history: set()
2019-11-15 10:23:02 | previous clicks now in history: set()
2019-11-15 10:49:12 | previous clicks now in history: set()
2019-11-15 10:55:11 | previous clicks now in history: set()
2019-11-15 11:19:56 | previous clicks now in history: set()
2019-11-15 11:48:54 | previous clicks now in history: set()
2019-11-15 12:44:09 | previous clicks now in history: set()
2019-11-15 13:01:37 | previous clicks now in history: set()
2019-11-15 13:11:50 | previous clicks now in history: set()
2019-11-15 13:27:12 | previous clicks now in history: set()
2019-11-15 14:00:39 | previous clicks now in history: set()
2019-11-15 15:31:37 | previous clicks now in history: set()

In [7]:
rows = user_data.reset_index(drop=True)

for i in range(1, len(rows)):
    previous_history = set(rows.iloc[i - 1]["history"].split())
    current_history = set(rows.iloc[i]["history"].split())

    added = current_history - previous_history
    removed = previous_history - current_history

    print(
        rows.iloc[i]["time"],
        "| added:", len(added),
        "| removed:", len(removed)
    )

2019-11-15 07:15:28 | added: 0 | removed: 0
2019-11-15 07:36:34 | added: 0 | removed: 0
2019-11-15 09:40:21 | added: 0 | removed: 0
2019-11-15 09:58:15 | added: 0 | removed: 0
2019-11-15 10:06:32 | added: 0 | removed: 0
2019-11-15 10:12:16 | added: 0 | removed: 0
2019-11-15 10:23:02 | added: 0 | removed: 0
2019-11-15 10:49:12 | added: 0 | removed: 0
2019-11-15 10:55:11 | added: 0 | removed: 0
2019-11-15 11:19:56 | added: 0 | removed: 0
2019-11-15 11:48:54 | added: 0 | removed: 0
2019-11-15 12:44:09 | added: 0 | removed: 0
2019-11-15 13:01:37 | added: 0 | removed: 0
2019-11-15 13:11:50 | added: 0 | removed: 0
2019-11-15 13:27:12 | added: 0 | removed: 0
2019-11-15 14:00:39 | added: 0 | removed: 0
2019-11-15 15:31:37 | added: 0 | removed: 0